global:
  scrape_interval: 1s

  external_labels:
    monitor: "example-app"

rule_files:

scrape_configs:
  - job_name: "prometheus"
    static_configs:
      - targets: ["localhost:9090"]

  - job_name: "flask"
    static_configs:
      - targets: ["45.135.164.232:5000"]
