apiVersion: v1
kind: Pod
metadata:
  name: flask
  labels:
    app: flask-helloworld
spec:
  containers:
  - name: flask
    image: my_flask:v2
    ports:
    - containerPort: 5000


---
apiVersion: v1
kind: Service
metadata:
  name: flask-service
spec:
  type: LoadBalancer
  #loadBalancerIP: 127.0.0.1
  ports:
  - port: 5000
    protocol: TCP
    targetPort: 5000
  selector:
    app: flask

